odoo:
  tty: true
  stdin_open: true
  restart: always
  build: ./odoo/
  command: ""
  ports:
    - "8069:8069"
    - "8071:8071"
  links:
    - db:db
  volumes:
    # for dev only (todo: add configuration files per env)
    - "./odoo/odoo-extra/:/opt/odoo/addons/odoo-extra"
    - "./odoo/odoo:/opt/odoo/sources"
    - "/opt/odoo-extra/runbot/static/nginx/:/etc/nginx/conf.d/"
  volumes_from:
    - data

nginx:
  restart: always
  image: nginx
  ports:
    - "80:80"
  volumes_from:
    - odoo
  links:
    - odoo:odoo

db:
  restart: always
  image: postgres:9.4
  env_file: .env
  environment:
    - DB_USER=odoo
    - DB_PASS=odoo
    - DB_NAME=runbot
  volumes_from:
    - data
  expose:
    - 5432

data:
  restart: always
  image: postgres:9.4
  volumes:
    - /var/lib/postgresql
    - /data/odoo
  command: "true"
